spring.application.name=eventos

server.port=8081

# Desactivar Base de Datos y JPA
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

logging.file.name=logs/app-dev.json
logging.structured.format.file=logstash
logging.structured.format.console=logstash

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true