{
 "title": "Observabilidad Microservicio Evento",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Estado de los servicios",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de memoria del microservicio Evento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"evento\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de solicitudes HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"evento\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errores HTTP del microservicio Evento",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"evento\", status=~\"4..|5..\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}